project_name: batimag
dist: ./bin
builds:
  - env:
      - CGO_ENABLED=1
    flags:
      - -trimpath
    ldflags:
      - -s -w
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
archives:
  - files:
      - LICENSE
      - README.md
      - config.example.yml
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
